#
#  qrest/formats/svg.rb  --  Build SVG
#

require "qrest/modules"
require "qrest/version"


module QRest

  class Modules

    def svg header: nil, dimen: nil, quiet_size: nil, title: nil, cls: nil, id: nil, output: nil
      header = true if header.nil?
      dimen      ||= "100px"
      quiet_size ||= 4
      title      ||= "QR Code"
      cls        ||= "qr"
      id         ||= self.class.svg_id
      output     ||= ""

      header and output << <<~EOT
        <?xml version="1.0" encoding="UTF-8"?>
      EOT
      full = size + 2*quiet_size
      output << <<~EOT
        <svg xmlns="http://www.w3.org/2000/svg"
            version="1.1" baseProfile="full"
            class="#{cls}" id="#{id}"
            width="#{dimen}" height="#{dimen}" viewBox="0 0 #{full} #{full}">
            <title>#{title}</title>
            <desc>Generated by #{QRest::NAME} #{QRest::VERSION}</desc>
      EOT
      each_field quiet_size do |ri,ci|
        output << <<~EOT % [ci,ri]
          <rect x="%3d" y="%3d" width="1" height="1" fill="black"/>
        EOT
      end
      output << <<~EOT
        </svg>
      EOT
      output
    end

    def html dimen: nil, quiet_size: nil, title: nil, output: nil
      output ||= ""
      output << <<~EOT
        <!DOCTYPE html>
        <html>
        <head>
          <meta charset="UTF-8">
          <title>Example Page with QR Code</title>
          <style>
            body    { background: #ddddee; }
            .qrcode { background: #ffffff; }
          </style>
        </head>
        <body>
          <h1>My self-generated QR Code</h1>
      EOT
      svg header: false, quiet_size: quiet_size, title: title, cls: "qrcode", output: output
      output << <<~EOT
          <hr>
          <pre>#{Time.now}</pre>
        </body>
        </html>
      EOT
    end

    class <<self
      def svg_id ; @id ||= "qr_000" ; @id.succ! ; end
    end

  end

end

